#define DEMANDCAPTUR           "http://nrega.ap.gov.in:9090/eMMS_Test/DemandCapture.aspx?Data="
#define REMANINGDAYS           "http://nrega.ap.gov.in:9090/eMMS_Test/RemainingDays.aspx?Code="
#define EMUSTER_ATTD           "http://nrega.ap.gov.in:9090/eMMS_Test/eMusters.aspx?Data="
#define SPLITJC_UPLOAD         "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateSplitJobCardInfo.aspx?Code="
#define SPLITJC_DOWNLD         "http://nrega.ap.gov.in:9090/eMMS_Test/SplitJobCardInfo.aspx?Code="
#define MCC_DEMAND_GROUPS      "http://nrega.ap.gov.in:9090/eMMS_Test/DownloadDemandCaptureDetails.aspx?Code="
#define MCC_DEMAND_WID         "http://nrega.ap.gov.in:9090/eMMS_Test/DownloadDemandAllocationDetails.aspx?Code="
#define POS_INFO_UP            "http://nrega.ap.gov.in:9090/eMMS_Test/POSManagement.aspx?Data=" 
#define MVO_MUSTER_UP          "http://nrega.ap.gov.in:9090/eMMS_Test/MVOMustersUpload.aspx?Data="
#define NO_DEMAND_GROUPS_UP    "http://nrega.ap.gov.in:9090/eMMS_Test/NotDemandedGroups.aspx?Data="
#define NO_WORK_UP             "http://nrega.ap.gov.in:9090/eMMS_Test/GPAbstractMusters.aspx?Data="
#define WAGEINFO_DOWN          "http://nrega.ap.gov.in:9090/eMMS_Test/DownloadedDays.aspx?Code="
#define DEMNDWORKALLOCN_UP  "http://nrega.ap.gov.in:9090/emms_Test/DemandAllocation.aspx?Data="
#define WORKS_DOWN             "http://nrega.ap.gov.in:9090/eMMS_Test/Works.aspx?Code="
#define GROUPALLOCAION_DOWN    "http://nrega.ap.gov.in:9090/eMMS_Test/SSSGroupsAllocation.aspx?Code="
#define HH_INFO                "http://nrega.ap.gov.in:9090/eMMS_Test/SSSInfo.aspx?Code="
#define MCC_WRKALLOC_REJC     "http://nrega.ap.gov.in:9090/eMMS_Test/RejectedDemandAllocationDetails.aspx?Code="
#define MCC_DEMAND_REJC       "http://nrega.ap.gov.in:9090/eMMS_Test/RejectedDemandCaptureDetails.aspx?Code="
#define BATCHINFO_DOWN        "http://nrega.ap.gov.in:9090/eMMS_Test/BatchCategoryDetails.aspx?Code="
#define UPDATE_REMAIN_DAYSRESPONSE "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateRemainingDays.aspx?Code="
#define UPDATE_Download_DAYSRESPONSE "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateDownloadedDays.aspx?Code="



#define UPDATEWRK_RESPONSE     "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateWorks.aspx?Code="
#define SSSINFO_RESPONSE       "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateSSSInfo.aspx?Code="
#define SSSGRUPALLOCN_RESPONSE "http://nrega.ap.gov.in:9090/eMMS_Test/UpdateSSSGroupsAllocation.aspx?Code="
